version: 0.2

phases:
  install:
    commands:
      - chmod +x mvnw
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./mvnw clean package -DskipTests
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - target/app.jar
  discard-paths: yes  